name: Build TemporalDenoiser

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Homebrew and gfortran
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gfortran

      - name: Install dependencies
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install -r requirements.txt

      - name: Debug rawpy, tifffile, and PySide6 installation
        run: |
          echo "Listing rawpy directory contents:"
          ls -R /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/rawpy || echo "rawpy directory not found"
          echo "Checking for libraw:"
          ls -l /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/rawpy/libraw || echo "libraw directory not found"
          echo "Listing all dylib files in rawpy/libraw:"
          find /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/rawpy/libraw -name "*.dylib" || echo "No dylib files found in rawpy/libraw"
          echo "Listing tifffile directory contents:"
          ls -R /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/tifffile || echo "tifffile directory not found"
          echo "Listing PySide6 directory contents:"
          ls -R /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/PySide6 || echo "PySide6 directory not found"
          echo "Listing all dylib files in PySide6:"
          find /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/PySide6 -name "*.dylib" || echo "No dylib files found in PySide6"

      - name: Debug cinemadng.py
        run: |
          echo "Contents of cinemadng.py:"
          cat temporal_denoiser/cinemadng.py || echo "cinemadng.py not found"

      - name: Debug libpython3.10.dylib path
        run: |
          echo "Checking for libpython3.10.dylib:"
          ls -l /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/libpython3.10.dylib || echo "libpython3.10.dylib not found"
          echo "Listing all dylib files in Python lib directory:"
          find /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib -name "*.dylib"

      - name: Build with PyInstaller
        env:
          PYTHONPATH: /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages
          LD_LIBRARY_PATH: /Users/runner/hostedtoolcache/Python/3.10.18/x64/lib
        run: |
          python3.10 -m PyInstaller --log-level DEBUG TemporalDenoiser.spec

      - name: Inspect app bundle dependencies
        run: |
          echo "Checking dynamic libraries in TemporalDenoiser executable:"
          otool -L dist/TemporalDenoiser.app/Contents/MacOS/TemporalDenoiser || echo "Executable not found"
          echo "Listing critical libraries in Resources:"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/libpython3.10.dylib || echo "libpython3.10.dylib not found"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/rawpy/libraw || echo "libraw not found"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/PySide6/Qt/lib || echo "Qt libraries not found"
          echo "Checking for app_icon.icns:"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/app_icon.icns || echo "app_icon.icns not found"

      - name: Inspect app bundle
        run: |
          ls -R dist/TemporalDenoiser.app/Contents/Resources
          ls -l dist/TemporalDenoiser.app/Contents/MacOS

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          APP_PATH="dist/TemporalDenoiser.app"
          DMG_NAME="TemporalDenoiser-$(date +'%Y%m%d').dmg"
          hdiutil create -volname "TemporalDenoiser" \
                         -srcfolder "$APP_PATH" \
                         -ov -format UDZO "dist_dmg/$DMG_NAME"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-dmg
          path: dist_dmg/*.dmg
