name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install numpy scipy opencv-python-headless rawpy imageio PySide6

      - name: Install py2app (GitHub fork)
        run: |
          pip install git+https://github.com/ronaldoussoren/py2app.git

      - name: Patch py2app for Python 3.10 compatibility
        run: |
          pip install importlib_resources
          recipe_dir=$(python -c "import py2app, inspect, os; print(os.path.join(os.path.dirname(inspect.getfile(py2app)), '_recipedefs'))")
          echo "Patching files in $recipe_dir"
          # Patch import statements
          find "$recipe_dir" -type f -name "*.py" -exec sed -i.bak 's/from importlib import resources/import importlib_resources as resources/' {} \;
          find "$recipe_dir" -type f -name "*.py" -exec sed -i.bak 's/import importlib\.resources as resources/import importlib_resources as resources/' {} \;
          # Patch type annotations and references
          find "$recipe_dir" -type f -name "*.py" -exec sed -i.bak 's/importlib\.resources\.abc/importlib_resources.abc/' {} \;
          # Avoid incorrect replacements
          find "$recipe_dir" -type f -name "*.py" -exec sed -i.bak 's/importlib\.importlib_resources/importlib_resources/' {} \;
          # Verify patching
          find "$recipe_dir" -type f -name "*.py" -exec grep -H "importlib_resources" {} \;
          # Check for erroneous importlib_importlib_resources
          if grep -r "importlib_importlib_resources" "$recipe_dir"; then
            echo "Error: Found incorrect 'importlib_importlib_resources' in patched files"
            exit 1
          fi

      - name: Display patched stdlib.py
        run: |
          stdlib_file=$(python -c "import py2app, inspect, os; print(os.path.join(os.path.dirname(inspect.getfile(py2app)), '_recipedefs', 'stdlib.py'))")
          echo "Contents of $stdlib_file:"
          cat "$stdlib_file"
        if: failure()

      - name: Build app with py2app
        run: |
          python setup.py py2app

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname "TemporalDenoiser" -srcfolder "dist/TemporalDenoiser.app" -ov -format UDZO "dist_dmg/TemporalDenoiser.dmg"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macOS
          path: dist_dmg/*.dmg
