name: Build TemporalDenoiser

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew and dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gfortran python@3.10 libraw
          echo "/usr/local/opt/python@3.10/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/python@3.10/libexec/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          /usr/local/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
          /usr/local/opt/python@3.10/bin/python3.10 -m pip install "setuptools<81" -r requirements.txt

      - name: Debug Homebrew Python and dependencies
        run: |
          echo "Homebrew Python version and path:"
          /usr/local/opt/python@3.10/bin/python3.10 --version
          which python3.10
          echo "Listing Homebrew Python lib directory:"
          ls -l /usr/local/opt/python@3.10/lib || echo "Python lib directory not found"
          echo "Searching for libpython3.10.dylib:"
          find /usr/local/Cellar/python@3.10 -name "libpython3.10.dylib" || echo "libpython3.10.dylib not found in Cellar"
          find /usr/local/opt -name "libpython3.10.dylib" || echo "libpython3.10.dylib not found in opt"
          find /usr/local/lib -name "libpython3.10.dylib" || echo "libpython3.10.dylib not found in /usr/local/lib"
          echo "Listing rawpy directory contents:"
          ls -R /usr/local/opt/python@3.10/lib/python3.10/site-packages/rawpy || echo "rawpy directory not found"
          echo "Checking for libraw in rawpy:"
          ls -l /usr/local/opt/python@3.10/lib/python3.10/site-packages/rawpy/libraw || echo "libraw directory not found"
          echo "Listing all dylib files in rawpy/libraw:"
          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/rawpy/libraw -name "*.dylib" || echo "No dylib files found in rawpy/libraw"
          echo "Listing system libraw:"
          ls -l /usr/local/opt/libraw/lib || echo "System libraw not found"
          echo "Searching for libraw dylib:"
          find /usr/local/opt/libraw/lib -name "libraw*.dylib" || echo "No libraw dylib found"
          echo "Listing tifffile directory contents:"
          ls -R /usr/local/opt/python@3.10/lib/python3.10/site-packages/tifffile || echo "tifffile directory not found"
          echo "Listing PySide6 directory contents:"
          ls -R /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6 || echo "PySide6 directory not found"
          echo "Listing all dylib files in PySide6:"
          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6 -name "*.dylib" || echo "No dylib files found in PySide6"
          echo "Searching for Qt frameworks in PySide6:"
          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6 -name "*.framework" || echo "No Qt frameworks found in PySide6"
          find /usr/local/opt -name "QtCore.framework" || echo "QtCore.framework not found"
          find /usr/local/opt -name "QtGui.framework" || echo "QtGui.framework not found"
          find /usr/local/opt -name "QtWidgets.framework" || echo "QtWidgets.framework not found"

      - name: Debug cinemadng.py
        run: |
          echo "Contents of cinemadng.py:"
          cat temporal_denoiser/cinemadng.py || echo "cinemadng.py not found"

      - name: Build with PyInstaller
        env:
          PYTHONPATH: /usr/local/opt/python@3.10/lib/python3.10/site-packages
          LD_LIBRARY_PATH: /usr/local/opt/python@3.10/lib:/usr/local/opt/libraw/lib
        run: |
          /usr/local/opt/python@3.10/bin/python3.10 -m PyInstaller --log-level DEBUG TemporalDenoiser.spec

      - name: Inspect app bundle dependencies
        run: |
          echo "Checking dynamic libraries in TemporalDenoiser executable:"
          otool -L dist/TemporalDenoiser.app/Contents/MacOS/TemporalDenoiser || echo "Executable not found"
          echo "Listing critical libraries in Resources:"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/libpython3.10.dylib || echo "libpython3.10.dylib not found"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/rawpy/libraw || echo "libraw not found"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/PySide6/Qt/lib || echo "Qt libraries not found"
          echo "Checking for app_icon.icns:"
          ls -l dist/TemporalDenoiser.app/Contents/Resources/app_icon.icns || echo "app_icon.icns not found"

      - name: Inspect app bundle
        run: |
          ls -R dist/TemporalDenoiser.app/Contents/Resources
          ls -l dist/TemporalDenoiser.app/Contents/MacOS

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          APP_PATH="dist/TemporalDenoiser.app"
          DMG_NAME="TemporalDenoiser-$(date +'%Y%m%d').dmg"
          hdiutil create -volname "TemporalDenoiser" \
                         -srcfolder "$APP_PATH" \
                         -ov -format UDZO "dist_dmg/$DMG_NAME"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-dmg
          path: dist_dmg/*.dmg
