name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.10 framework
        run: |
          curl -o python-installer.pkg https://www.python.org/ftp/python/3.10.8/python-3.10.8-macos11.pkg
          sudo installer -pkg python-installer.pkg -target /
          # Debug: List Python-related files to verify installation
          echo "Listing Python binaries in /usr/local/bin:"
          ls -l /usr/local/bin/python* /usr/local/bin/pip* || echo "No Python binaries in /usr/local/bin"
          echo "Listing Python framework:"
          ls -l /Library/Frameworks/Python.framework/Versions/3.10/ || echo "No Python framework in expected location"
          echo "Listing Python library:"
          ls -l /Library/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib || echo "No libpython3.10.dylib found"
          # Verify Python and pip versions
          /usr/local/bin/python3 --version || echo "Python 3 not found in /usr/local/bin"
          /usr/local/bin/pip3 --version || echo "pip3 not found in /usr/local/bin"

      - name: Install dependencies
        run: |
          /usr/local/bin/pip3 install --upgrade pip
          /usr/local/bin/pip3 install -r requirements.txt
          /usr/local/bin/pip3 install pyinstaller==6.15.0

      - name: Debug rawpy and tifffile installation
        run: |
          echo "Listing rawpy directory contents:"
          ls -R /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rawpy || echo "rawpy directory not found"
          echo "Checking for libraw:"
          ls -l /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rawpy/libraw || echo "libraw directory not found"
          echo "Listing tifffile directory contents:"
          ls -R /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tifffile || echo "tifffile directory not found"

      - name: Debug cinemadng.py
        run: |
          echo "Contents of cinemadng.py:"
          cat temporal_denoiser/cinemadng.py || echo "cinemadng.py not found"

      - name: Build app with PyInstaller
        run: |
          export MACOSX_DEPLOYMENT_TARGET=12.0
          /usr/local/bin/python3 -m PyInstaller TemporalDenoiser.spec --clean --noconfirm --log-level DEBUG

      - name: Inspect app bundle
        run: |
          echo "Listing app bundle Frameworks:"
          ls -R dist/TemporalDenoiser.app/Contents/Frameworks || echo "No Frameworks directory found"
          echo "Listing app bundle Resources:"
          ls -R dist/TemporalDenoiser.app/Contents/Resources || echo "No Resources directory found"
        if: always()

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          APP_PATH="dist/TemporalDenoiser.app"
          DMG_NAME="TemporalDenoiser-$(date +'%Y%m%d').dmg"
          hdiutil create -volname "TemporalDenoiser" \
                         -srcfolder "$APP_PATH" \
                         -ov -format UDZO "dist_dmg/$DMG_NAME"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-dmg
          path: dist_dmg/*.dmg
