name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.10 framework
        run: |
          curl -o python-installer.pkg https://www.python.org/ftp/python/3.10.8/python-3.10.8-macos11.pkg
          sudo installer -pkg python-installer.pkg -target /
          /Applications/Python\ 3.10/bin/pip3 install --upgrade pip
          /Applications/Python\ 3.10/bin/pip3 install -r requirements.txt
          /Applications/Python\ 3.10/bin/pip3 install pyinstaller

      - name: Build app with PyInstaller
        run: |
          export MACOSX_DEPLOYMENT_TARGET=12.0
          /Applications/Python\ 3.10/bin/python3 -m PyInstaller TemporalDenoiser.spec --clean --noconfirm --verbose

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          APP_PATH="dist/TemporalDenoiser.app"
          DMG_NAME="TemporalDenoiser-$(date +'%Y%m%d').dmg"
          hdiutil create -volname "TemporalDenoiser" \
                         -srcfolder "$APP_PATH" \
                         -ov -format UDZO "dist_dmg/$DMG_NAME"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-dmg
          path: dist_dmg/*.dmg
