name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install git+https://github.com/ronaldoussoren/py2app.git
          python -m pip install numpy scipy opencv-python-headless rawpy imageio PySide6

          # pip install importlib_resources

      - name: Install backport for importlib.resources
        run: pip install importlib_resources

      - name: Build .app bundle
        run: |
          python setup.py py2app

      - name: Verify __boot__.py does not import pkg_resources
        run: |
          if grep -q "pkg_resources" dist/TemporalDenoiser.app/Contents/Resources/__boot__.py; then
            echo "❌ ERROR: __boot__.py still imports pkg_resources. Check setup.py (use_pkg_resources=False)."
            exit 1
          else
            echo "✅ Verified: __boot__.py is clean (no pkg_resources)."
          fi    

      - name: Cleanup unwanted packages
        run: |
          rm -rf "dist/TemporalDenoiser.app/Contents/Resources/lib/python3.10/pkg_resources"
          rm -rf "dist/TemporalDenoiser.app/Contents/Resources/lib/python3.10/setuptools*"
          rm -rf "dist/TemporalDenoiser.app/Contents/Resources/lib/python3.10/jaraco*"

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname TemporalDenoiser \
                         -srcfolder dist/TemporalDenoiser.app \
                         -ov -format UDZO dist_dmg/TemporalDenoiser.dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macOS
          path: dist_dmg/*.dmg
