name: Build-macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install pyinstaller PySide6 numpy scipy opencv-python rawpy imageio

      - name: Build app with PyInstaller
        run: |
          pyinstaller TemporalDenoiser.spec

      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          hdiutil create dist/dmg/TemporalDenoiser.dmg \
            -volname "TemporalDenoiser" \
            -srcfolder dist/TemporalDenoiser \
            -ov -format UDZO

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macos
          path: dist/dmg/TemporalDenoiser.dmg

