name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install numpy scipy opencv-python-headless rawpy imageio PySide6

      - name: Install py2app (GitHub fork)
        run: |
          pip install git+https://github.com/ronaldoussoren/py2app.git

      - name: Patch py2app for Python 3.10 compatibility
        run: |
          # Replace importlib.resources.abc with importlib_resources.abc
          sed -i.bak 's/importlib\.resources\.abc/importlib_resources.abc/g' $(python -c "import py2app, inspect, os; print(os.path.dirname(inspect.getfile(py2app)))")/_recipedefs/stdlib.py || true
          pip install importlib_resources

      - name: Build app with py2app
        run: |
          python setup.py py2app

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname "TemporalDenoiser" -srcfolder "dist/TemporalDenoiser.app" -ov -format UDZO "dist_dmg/TemporalDenoiser.dmg"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macOS
          path: dist_dmg/*.dmg
