name: Build macOS App (PyInstaller)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build app with PyInstaller
        env:
          # ensure the produced binary targets macOS 12+ ABI
          MACOSX_DEPLOYMENT_TARGET: "12.0"
        run: |
          pyinstaller --clean --noconfirm TemporalDenoiser.spec
          test -d "dist/TemporalDenoiser.app" || (echo "App bundle not found!" && exit 1)

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          DMG_NAME="TemporalDenoiser_${{ github.run_number }}.dmg"
          hdiutil create -volname "TemporalDenoiser" \
                         -srcfolder "dist/TemporalDenoiser.app" \
                         -ov -format UDZO "dist_dmg/$DMG_NAME"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: TemporalDenoiser-macOS
          path: dist_dmg/*.dmg
